blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('^summernote/', include('django_summernote.urls')),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),  # allauth
    path('ticket/', include('ticket.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.news_list, name='list_news'),
    path('single/<int:pk>', views.new_single, name='new_single'),
    path('filter/<int:pk>', views.news_filter, name='news_filter'),
]

blog/ticket/urls.py
from . import views
from django.urls import path

urlpatterns = [
    #path('', views.MyView.as_view()),
    path('add_ticket/', views.AddTicket.as_view()),
    path('list_ticket/', views.ListTicket.as_view(), name='list_ticket'),
    path('update_ticket/<int:pk>', views.UpdateTicket.as_view(), name='update_ticket'),
]

blog/news/models.py
from django.db import models
from django.contrib.auth import get_user_model  # берем стандартную модель юзера

User = get_user_model()  # создаем класс юзера


class Category(models.Model):
    """Класс категорий"""
    title = models.CharField("Название", max_length=50)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.title


class Tag(models.Model):
    """Класс тегов статей"""
    title = models.CharField("Тэг", max_length=50)

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"

    def __str__(self):
        return self.title


class News(models.Model):
    """Класс новостей"""
    user = models.ForeignKey(  # автор статьи
        User,
        verbose_name="Автор",
        on_delete=models.CASCADE)  # при удалении юзера удаляем все его статьи

    category = models.ForeignKey(  # категория статьи
        Category,
        verbose_name="Категория",
        on_delete=models.SET_NULL,  # при удалении категории поле устанавливается в NULL
        null=True)  # категория в статье может отсутствовать

    title = models.CharField("Заголовок", max_length=100)  # Заголовок статьи
    text_min = models.TextField("Превью", max_length=350)  # превью статьи
    text = models.TextField("Текст статьи")  # полный текст статьи
    tags = models.ManyToManyField(Tag, verbose_name="Тэги")  # У одной статьи
    created = models.DateTimeField("Дата создания", auto_now_add=True)  # дата создания статьи
    description = models.CharField("Описание", max_length=100)
    keywords = models.CharField("Ключевые слова", max_length=50)


    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"

    def __str__(self):
        return self.title


class Comments(models.Model):
    """Класс комментариев к новостям"""
    user = models.ForeignKey(
        User,
        verbose_name='Пользователь',
        on_delete=models.CASCADE)
    new = models.ForeignKey(
        News,
        verbose_name='Новость',
        on_delete=models.CASCADE)
    text = models.TextField('Комментарий')
    created = models.DateTimeField('Дата добавления', auto_now_add=True, null=True)
    moderation = models.BooleanField('Модерация', default=False)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def __str__(self):
        return f'{self.user}'

blog/ticket/models.py
from django.db import models
from django.contrib.auth.models import User


class CategoryTicket(models.Model):
    """Категория тикетов"""
    title = models.CharField('Категория', max_length=50)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Ticket(models.Model):
    """Класс тикетов"""
    user = models.ForeignKey(User,
                             verbose_name='Пользователь',
                             on_delete=models.CASCADE)

    category = models.ForeignKey(CategoryTicket,
                                 verbose_name='Категория',
                                 on_delete=models.CASCADE)

    title = models.CharField('Тема', max_length=100)
    text = models.TextField('Текст письма', max_length=1000)

    class Meta:
        verbose_name = 'Тикет'
        verbose_name_plural = 'Тикеты'

    def __str__(self):
        return f'{self.text} {self.user}'

blog/news/forms.py
from django.forms import ModelForm
from .models import Comments

class CommentForm(ModelForm):
    """Форма комментариев к статьям"""
    class Meta:
        model = Comments
        fields = ('text', )

blog/ticket/forms.py
from django import forms
from .models import Ticket

class AddTicketForm(forms.ModelForm):
    """Форма добавления тикетов"""
    class Meta:
        model = Ticket
        fields = ('category', 'title', 'text')

blog/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import News, Comments
from .forms import CommentForm

from datetime import datetime, timedelta


def news_list(request):
    """Вывод всех новостей"""
    news = News.objects.all()
    return render(request, "news/news_list.html", {'news': news})


def new_single(request, pk):
    """Вывод полной статьи"""
    new = get_object_or_404(News, id=pk)
    # закоментим, чтобы выводить коменты не через views, а через шаблон
    # но это не совсем правильно!
    # правильнее всю логику обработки запросов выносить во views
    comment = Comments.objects.filter(new=pk, moderation=True)

    # если POST запрос, форму обрабатываем и сохраняем
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.new = new
            form.save()
            return redirect(new_single, pk)  # редиректимся на страницу новости
    else:  # если GET запрос, форму создаем
        form = CommentForm()
    return render(request, 'news/new_single.html',
                  {
                      'new': new,
                      'comments': comment,
                      'form': form
                  })


def news_filter(request, pk):
    """ Фильтр статей по дате
    """
    news = News.objects.all()
    if pk == 1:  # фильтр на неделю
        now = datetime.now() - timedelta(weeks=1)
        news = news.filter(created__gte=now)  # __gte означает "больше или равно"
    elif pk == 2:  # фильтр на месяц
        now = datetime.now() - timedelta(days=30)
        news = news.filter(created__gte=now)
    return render(request, 'news/news_list.html', {'news': news})

blog/ticket/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.http import HttpResponse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.urls import reverse

from .models import Ticket
from .forms import AddTicketForm

# class MyView(View):
#     def get(self, request, *args, **kwargs):
#         return HttpResponse('classes django')
#
#
# class MyTemplateView(TemplateView):  # специальная вьюха для работы с шаблонами
#     template_name = 'ticket/addticket.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(MyTemplateView, self).get_context_data(**kwargs)
#         context['text'] = 'Hello world!'
#         return context


class AddTicket(CreateView):
    """
    Добавление тикета
    """
    model = Ticket
    form_class = AddTicketForm
    template_name = 'ticket/addticket.html'

    # переопределям этот метод только из-за того, что
    # нужно получить юзера
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()  # добавление инфы из заполненной формы в бд
        return redirect('/ticket/add_ticket/')

    def success_url(self):
        return redirect('/add_ticket/')


class ListTicket(ListView):
    """Список тикетов пользователя"""
    model = Ticket
    #queryset = Ticket.objects.all()
    context_object_name = 'tickets'
    template_name = 'ticket/list_ticket.html'

    def get_queryset(self):  # в списке тикетов выдаем только тикеты текущего авторизованного юзера
        return Ticket.objects.filter(user=self.request.user)


class UpdateTicket(UpdateView):
    """Редактирование тикета"""
    model = Ticket
    form_class = AddTicketForm
    template_name = 'ticket/update_ticket.html'

    def get_success_url(self):
        return reverse('list_ticket')

blog/news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block desc %}{% endblock desc %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block content %}

    {% endblock content %}
</body>
</html>

blog/news/templates/news/base.html
{% extends 'base.html' %}


{% block desc %}{% endblock desc %}
{% block keywords %}{% endblock keywords %}
{% block title %}{% endblock title %}

{% block search %}

{% endblock search %}

{% block content %}

{% endblock content %}

blog/news/templates/news/new_single.html
{% extends 'news/base.html' %}


{% block desc %}{{ new.description }}{% endblock desc %}
{% block keywords %}{{ new.keywords }}{% endblock keywords %}
{% block title %}{{ new.title }}{% endblock title %}


{% block content %}

    <h1>{{ new.title }}</h1>
    <p>{{ new.text | safe }}</p><hr>


    Категория: {{ new.category }}<br>
    Тэги: {% for tag in new.tags.all %}
        {{ tag.title }}
    {% endfor %} <br>
    Автор: {{ new.user }} - {{ new.created }}  <hr>

    <h4>Комментарии</h4>
    {% for comment in comments %}
        Пользователь: {{ comment.user }} <br>
        {{ comment.text }} <br>
        Добавлен: {{ comment.created }} <br><br>
    {% endfor %}
<!--    {% for comment in new.comments_set.all %}-->
<!--        Пользователь: {{ comment.user }} <br>-->
<!--        {{ comment.text }} <br>-->
<!--        Добавлен: {{ comment.created }} <br><br>-->
<!--    {% endfor %}-->


<!--Сделаем так, чтобы комментарий мог оставлять только пользователь,-->
<!--зарегистрировавшийся или авторизовавшийся на сайте-->
    {% if user.is_active %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Отправить</button>
        </form>
    {% else %}
        <h4>Чтобы оставить комментарий, авторизуйтесь!</h4>
    {% endif %}

{% endblock content %}

blog/news/templates/news/news_list.html
{% extends 'news/base.html' %}

{% block search %}
    <a href="{% url 'news_filter' pk=1 %}"><button>Неделя</button></a>
    <a href="{% url 'news_filter' pk=2 %}"><button>Месяц</button></a>
    <a href="{% url 'news_filter' pk=3 %}"><button>Все</button></a>
{% endblock search %}
<!--при нажатии на кнопку передается некая команда pk,-->
<!--которая и запускает во вьюхе отработку в бд-->
{% block content %}
    {% for new in news %}
        <h2><a href="{% url 'new_single' pk=new.id %}">{{ new.title }}</a></h2>
        <p>{{ new.text_min | safe }}</p>
        <p>{{ new.created }}</p>
    {% endfor %}
{% endblock content %}

blog/ticket/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block desc %}{% endblock desc %}">
    <meta name="keywords" content="{% block keywords %}{% endblock keywords %}">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
    <div class="page">
    <input type="text" value="" name="search" placeholder="Поиск...">
    {% block search %}

    {% endblock search %}
        <div class="main">
        {% block content %}

        {% endblock content %}
        </div>
    </div>
</body>
</html>

blog/ticket/templates/ticket/addticket.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>

    </form>

{% endblock content %}

blog/ticket/templates/ticket/list_ticket.html
{% extends 'base.html' %}
{% block content %}
    {% for ticket in tickets %}
        <h5>{{ ticket.title }}</h5>
        <p>{{ ticket.text }}</p>
        <a href="{% url 'update_ticket' pk=ticket.id %}">Редактировать</a>
        <br><br>

    {% endfor %}
{% endblock content %}

blog/ticket/templates/ticket/update_ticket.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
{% endblock content %}